(define (problem go-to) (:domain example)
	(:objects
		bot - robot
		redroom greenroom duckroom ballroom ballroom2 startroom midroom red green ducks balls - room
	)
	(:init
		(in bot green)
		
		(cango startroom midroom)
		(cango startroom ducks)
		(cango midroom ballroom)
		(cango midroom duckroom)
		(cango greenroom redroom)
		(cango ballroom ballroom2)
		(cango ballroom2 duckroom)
		(cango ballroom2 ducks)
		(cango duckroom ducks)
		(cango ducks duckroom)
		(cango redroom greenroom)
		(cango duckroom ballroom)
		(cango greenroom green)
		(cango green greenroom)
		(cango red green)
		(cango red greenroom)
		(cango greenroom red)
		(cango green red)
		(cango green redroom)
		(cango redroom green)
		(cango duckroom redroom)
		(cango ballroom greenroom)
		(cango redroom red)
		(cango red redroom)
		(cango redroom duckroom)
		(cango greenroom ballroom)
		(cango ballroom balls)
		(cango balls ballroom)
	)
	(:goal
		(in bot green)
	)
    )